### ISSUE TITLE
Question: Changing Avatar

### ISSUE THREAD

**Issue by oleteacher** [HB0N0/AvataaarsJs#1]
Really like what you got going here:)

I can see kids in classroom loving this. How can I change the default avatar person?

Just can't seem to grasp that...

Thanks!

**Comment by HB0N0** [comment]
If you want to change the default avatar appearance simply modify the `defaultOptions` parameter of the Avataaars object. The defaultOptions can contain every option availible also in the avatars.create() method.

```javascript
// Run this prior to creating your first avatar
Avataaars.defaultOptions = {
    style: 'circle',
    eyes: 'happy',
    mouth: 'smile',
    /*  ...  */
};
```

Alternatively you could also modify the defaultOptions object directly in the library (line 2) which may be easier for educational purposes if you want to hand this library out to your students and keep the usage simple.

Let me know if I could help you 😃

**Comment by oleteacher** [comment]
Sometime one cannot see the forest because the trees are blocking their view :)

I was thinking there were different background avatar models (male, female, etc.) when in fact there are only accessories and expressions.

Working great, thank you!
